### ISSUE TITLE
v3.1.0 having missing method errors

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/assembly#38]
for example, from `jp2-create` in -test:

```
 INFO [2016-03-04 11:55:41] (3392)  :: druid:yt587cr2141 processing
ERROR [2016-03-04 11:55:41] (3392)  :: undefined method `get_workflow_status' for nil:NilClass
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/lyber-core-4.0.3/lib/lyber_core/robot.rb:92:in `item_queued?'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/lyber-core-4.0.3/lib/lyber_core/robot.rb:67:in `work'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/lyber-core-4.0.3/lib/lyber_core/robot.rb:20:in `perform'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:227:in `perform'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
lib/rake/application.rb:115:in `run_with_threads'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/bin/rake:23:in `load'
/home/lyberadmin/assembly/shared/bundle/ruby/2.2.0/bin/rake:23:in `<main>'
ERROR [2016-03-04 11:55:41] (3392)  :: Cannot set druid:yt587cr2141 to status='error'
undefined method `update_workflow_error_status' for nil:NilClass
```

**Comment by cbeer** [comment]
Can you try updating dor-services to 5.5?

**Comment by drh-stanford** [comment]
Thanks! I thought I did that yesterday :(. I put in a PR for this.
